replicaCount: 2

image:
  repository: python
  tag: 3.11-slim
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  className: nginx
  host: flask.homelab
