apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: lab-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flask-web
  template:
    metadata:
      labels:
        app: flask-web
    spec:
      containers:
      - name: flask-container
        image: {{ .Values.image }}
        imagePullPolicy: Never
        ports:
        - containerPort: 5000